return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "1.3.2",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 60,
  height = 36,
  tilewidth = 32,
  tileheight = 30,
  nextlayerid = 5,
  nextobjectid = 23,
  properties = {},
  tilesets = {},
  layers = {
    {
      type = "imagelayer",
      id = 2,
      name = "Background",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = -400,
      image = "../Images/ShipPlaceholder.png",
      properties = {}
    },
    {
      type = "objectgroup",
      id = 3,
      name = "Collider",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "",
          shape = "rectangle",
          x = 652,
          y = 152,
          width = 643,
          height = 241.727,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "ellipse",
          x = 118,
          y = 249.091,
          width = 616.818,
          height = 617.515,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 580,
          y = 653,
          width = 1299,
          height = 240,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1802,
          y = 468,
          width = 163.5,
          height = 223,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "polygon",
          x = 1251,
          y = 384,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 4 },
            { x = 45.5, y = 58.25 },
            { x = 562, y = 116.727 },
            { x = 602, y = -47 },
            { x = 0, y = -123 }
          },
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 910.25,
          y = 366,
          width = 15,
          height = 170.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 811.5,
          y = 523,
          width = 100.5,
          height = 13.25,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 712.5,
          y = 524,
          width = 55.5,
          height = 13.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1055.5,
          y = 386,
          width = 17,
          height = 149.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1291,
          y = 438.5,
          width = 12.5,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1190,
          y = 522,
          width = 107.5,
          height = 15,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1055.75,
          y = 521.875,
          width = 97,
          height = 13.25,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1551.75,
          y = 437,
          width = 12.5,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 4,
      name = "Ladders",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 17,
          name = "",
          type = "trigger",
          shape = "rectangle",
          x = 767.75,
          y = 488.25,
          width = 42.5,
          height = 164.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "trigger",
          shape = "rectangle",
          x = 1148.08,
          y = 489,
          width = 42.5,
          height = 166,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
